### ISSUE TITLE
future imports

### ISSUE THREAD

**Issue by manuSrep** [ilastik/pytemplate#1]
I recognized, lot's of us still work with python 2.7 It might be helpful to advice (new) students also starting with python 2.7  to do all the future imports:

from **future** import division, absolute_import, unicode_literals, print_function

What do you think?

**Comment by chaubold** [comment]
This is actually a very good idea, as we're planning to move ilastik to Python 3 in the not too distant future. I'll adjust the readme and mention this as another _good practice_.
